version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: SecurePassword123!
      MYSQL_DATABASE: driptee_db
      MYSQL_USER: driptee_user
      MYSQL_PASSWORD: UserPassword456!
    volumes:
      - ./driptee_db.sql:/docker-entrypoint-initdb.d/driptee_db.sql
